language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
  - mkdir build
  - cd build
  - cmake ..

script: make -j $(getconf _NPROCESSORS_ONLN)
